payment_transaction.rb: process with pid 11921 started.
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query': Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2): SELECT `payment_transactions`.* FROM `payment_transactions`  WHERE `payment_transactions`.`type` IN ('PaymentTransaction::Normal') AND `payment_transactions`.`aasm_state` IN ('unconfirm', 'confirming') (ActiveRecord::StatementInvalid)
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
	from /root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/payment_transaction_ctl:6:in `<main>'
payment_transaction.rb: process with pid 14445 started.
