# Logfile created on 2016-11-19 13:01:57 by logger.rb/47272
I, [2016-11-19T13:01:57.462266 #11921]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2016-11-19T13:01:57.462408 #11921] ERROR -- : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (Mysql2::Error)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
/root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/payment_transaction_ctl:6:in `<main>'
I, [2016-11-19T13:01:57.467330 #11921]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2016-11-19T13:01:57.467918 #11921] ERROR -- : stream closed (IOError)

E, [2016-11-19T13:01:57.468099 #11921] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2016-11-19T13:01:57.468170 #11921] ERROR -- : stack level too deep (SystemStackError)

E, [2016-11-19T13:01:57.468329 #11921] ERROR -- : exception reentered (fatal)

E, [2016-11-19T13:01:57.479078 #11921] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2016-11-19T13:01:57.494316 #11921] ERROR -- : no such frame (ArgumentError)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:628:in `open_logfile'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:318:in `new'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2016-11-19T13:01:57.497271 #11921] ERROR -- : No such file or directory @ rb_sysopen - /root/coinroots/log/payment_transaction.rb.log (Errno::ENOENT)
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:628:in `open_logfile'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:318:in `new'
/root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2016-11-19T13:01:57.497372 #11921] ERROR -- : no such frame (ArgumentError)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:447:in `rescue in log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
/root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/payment_transaction_ctl:6:in `<main>'
E, [2016-11-19T13:01:57.497450 #11921] ERROR -- : Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2): SELECT `payment_transactions`.* FROM `payment_transactions`  WHERE `payment_transactions`.`type` IN ('PaymentTransaction::Normal') AND `payment_transactions`.`aasm_state` IN ('unconfirm', 'confirming') (ActiveRecord::StatementInvalid)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
/root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/payment_transaction_ctl:6:in `<main>'
E, [2016-11-19T13:01:57.497516 #11921] ERROR -- : no such frame (ArgumentError)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
/root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/payment_transaction_ctl:6:in `<main>'
E, [2016-11-19T13:01:57.497570 #11921] ERROR -- : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (Mysql2::Error)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/querying.rb:36:in `find_by_sql'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:587:in `exec_queries'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:471:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation.rb:220:in `to_a'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:12:in `each'
/root/coinroots/lib/daemons/payment_transaction.rb:18:in `<top (required)>'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/payment_transaction_ctl:6:in `<main>'
